<?php

namespace app\controllers;

use Yii;
use app\models\Activity;
use yii\db\Exception;
use yii\web\Application;

class ActivityController extends \yii\web\Controller
{

    public $prevPage;


    public function actions(){




    }

    public function afterAction($action, $result)
    {
        $session = Yii::$app->session;
        $this->prevPage = $session->get('prevPage');

        $session->set('prevPage',
            Yii::$app->request->url);


        return parent::afterAction($action, $result); // TODO: Change the autogenerated stub
    }


    public function actionIndex()
    {


        $activities = \Yii::$app->activity->getActivityList();


        return $this->render('index',
            [
                'prevPage' => $this->prevPage,
                'activities' => $activities

            ]

        );
    }

    public function actionView(){




        $activity = \Yii::$app->activity->getActivityById(Yii::$app->request->get('actv_id'));


        return $this->render('view',
            [
                'model'=> $activity, 'prevPage' => $this->prevPage,
            ]
        );
    }


    public function actionCreate()
    {
        //return "Создание активности";
        $activity = \Yii::$app->activity->getModel();

        if ($activity->load(Yii::$app->request->post())){
            if ($activity->validate()) {
                //return "Создание активности";

                try{
                \Yii::$app->activity->save($activity);

                }
                catch (Exception $e)
                {
                    return $this->render('create',
                        [
                            'model'=> $activity,
                            'error'=>'Ошибка при сохранении События'
                        ]
                    );
                }
                return $this->render('view',
                    [
                        'model'=> $activity
                    ]
                );

            }

        }

        return $this->render('create',
            [
                'model'=> $activity,'error'=>''
            ]
        );

    }

}
